/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.os_project.GUI;

import com.mycompany.os_project.Models.GanttRecord;
import com.mycompany.os_project.Models.Result;

import javax.swing.*;
import java.awt.*;

public class GanttChartPanel extends javax.swing.JPanel {

    private Result result;

    public GanttChartPanel(Result result) {

        this.result = result;

        setPreferredSize(new Dimension(800, 120));

        setBackground(Color.WHITE);
    }

    @Override
    protected void paintComponent(Graphics g) {

        super.paintComponent(g);

        int x = 20;

        int y = 30;

        int height = 50;

        for (GanttRecord r : result.ganttChart) {

            int width =
                    (r.endTime - r.startTime) * 40;

            g.drawRect(x, y, width, height);

            g.drawString(
                    r.processId,
                    x + width / 2,
                    y + 25
            );

            g.drawString(
                    String.valueOf(r.startTime),
                    x,
                    y + 70
            );

            x += width;
        }

        if (!result.ganttChart.isEmpty()) {

            GanttRecord last =
                    result.ganttChart.get(
                            result.ganttChart.size() - 1
                    );

            g.drawString(
                    String.valueOf(last.endTime),
                    x,
                    y + 70
            );
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
