/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
import Models.Result;
import Models.Process;
import Models.Result;
import javax.swing.table.DefaultTableModel;
public class ResultFrame extends javax.swing.JFrame {
    private Result rr;
    private Result srtf;

    public ResultFrame(Result rrResults, Result srtfResults) {
        initComponents();
        
        // 1. التخزين أولاً (مهم جداً)
        this.rr = rrResults;
        this.srtf = srtfResults;
        
        // 2. التحقق إن البيانات وصلت فعلاً
        if (this.rr != null) { // الخطوة 2: العرض بعد التخزين
            displayData();
            }
    }
private void displayData() {
    // ملء جدول Round Robin
    DefaultTableModel modelRR = (DefaultTableModel) tableRR.getModel(); // تأكد من اسم الجدول عندك
    modelRR.setRowCount(0);
    for (Process p : rr.processes) {
        modelRR.addRow(new Object[]{
            "P" + p.id, p.arrivalTime, p.burstTime, 
            p.completionTime, p.waitingTime, p.turnaroundTime, p.responseTime
        });
    }
    // تحديث الـ Labels بالأسماء الصح من كلاس Result
    lblAvgWaitRR.setText("Avg WT: " + String.format("%.2f", rr.avgWT));

    // ملء جدول SRTF
    DefaultTableModel modelSRTF = (DefaultTableModel) tableSRTF.getModel();
    modelSRTF.setRowCount(0);
    for (Process p : srtf.processes) {
        modelSRTF.addRow(new Object[]{
            "P" + p.id, p.arrivalTime, p.burstTime, 
            p.completionTime, p.waitingTime, p.turnaroundTime, p.responseTime
        });
    }
    lblAvgWaitSRTF.setText("Avg WT: " + String.format("%.2f", srtf.avgWT));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSRTF = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableRR = new javax.swing.JTable();
        lblAvgWaitRR = new javax.swing.JLabel();
        lblAvgWaitSRTF = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Round Robin Results");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("SRTF Results");

        tableSRTF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PID", "AT", "BT", "CT", "WT", "TAT", "RT"
            }
        ));
        jScrollPane1.setViewportView(tableSRTF);

        tableRR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PID", "AT", "BT", "CT", "WT", "TAT", "RT"
            }
        ));
        jScrollPane3.setViewportView(tableRR);

        lblAvgWaitRR.setText("lblAvgWaitRR");

        lblAvgWaitSRTF.setText("lblAvgWaitSRTF");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblAvgWaitRR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvgWaitSRTF))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvgWaitRR)
                    .addComponent(lblAvgWaitSRTF))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            new InputFrame().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAvgWaitRR;
    private javax.swing.JLabel lblAvgWaitSRTF;
    private javax.swing.JTable tableRR;
    private javax.swing.JTable tableSRTF;
    // End of variables declaration//GEN-END:variables
}
